# Generated by Django 6.0.3 on 2026-03-06 19:40

import django.core.validators
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_shop_is_flagged_shop_onboarded_by_user_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to=services.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), services.models.validate_file_size]),
        ),
    ]
